### PR TITLE
Update "New game" wizard

### PR DESCRIPTION
**Pull request by hansfn**
1st division is also using Escore / Datavolley.

### CODE REVIEW

**Comment by hansfn** [comment]
A trivial PR and a change that is not needed for existing users, but for new (1st division) users this was confusing. (And I got wrong advice at least from one source.)

**Review by tutturen — APPROVED** [review]

**Comment by hansfn** [comment]
@tutturen Is the update of [the website](http://blusstv.volleytv.no/) manual? It doesn't seem to be a nightly job at least. If it is manual, please include the latest logo update  (#13) before running the job.

**Comment by tutturen** [comment]
Det er @oveien som styrer den nettsiden.

**Comment by hansfn** [comment]
Takk, men har dialog med Øystein på OSVB sin Slack.

**Pull request merged**
